// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Role struct {
	ID          int64
	Name        string
	Description sql.NullString
}

type User struct {
	ID        int64
	Email     string
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Theme     string
}

type UserRole struct {
	UserID int64
	RoleID int64
}
