// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nav_items.sql

package repository

import (
	"context"
	"database/sql"
	"strings"
)

const assignRoleToNavItem = `-- name: AssignRoleToNavItem :exec
INSERT OR IGNORE INTO nav_item_roles (nav_item_id, role_id)
VALUES (?, ?)
`

type AssignRoleToNavItemParams struct {
	NavItemID int64
	RoleID    int64
}

func (q *Queries) AssignRoleToNavItem(ctx context.Context, arg AssignRoleToNavItemParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToNavItem, arg.NavItemID, arg.RoleID)
	return err
}

const clearNavItemRoles = `-- name: ClearNavItemRoles :exec
DELETE FROM nav_item_roles
WHERE nav_item_id = ?
`

func (q *Queries) ClearNavItemRoles(ctx context.Context, navItemID int64) error {
	_, err := q.db.ExecContext(ctx, clearNavItemRoles, navItemID)
	return err
}

const createNavItem = `-- name: CreateNavItem :one
INSERT INTO nav_items (name, url, icon, parent_id, sort_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, url, icon, parent_id, sort_order, created_at, updated_at
`

type CreateNavItemParams struct {
	Name      string
	Url       string
	Icon      sql.NullString
	ParentID  sql.NullInt64
	SortOrder sql.NullInt64
}

func (q *Queries) CreateNavItem(ctx context.Context, arg CreateNavItemParams) (NavItem, error) {
	row := q.db.QueryRowContext(ctx, createNavItem,
		arg.Name,
		arg.Url,
		arg.Icon,
		arg.ParentID,
		arg.SortOrder,
	)
	var i NavItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNavItem = `-- name: DeleteNavItem :exec
DELETE FROM nav_items
WHERE id = ?
`

func (q *Queries) DeleteNavItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNavItem, id)
	return err
}

const getNavItemByID = `-- name: GetNavItemByID :one
SELECT id, name, url, icon, parent_id, sort_order, created_at, updated_at
FROM nav_items
WHERE id = ?
`

func (q *Queries) GetNavItemByID(ctx context.Context, id int64) (NavItem, error) {
	row := q.db.QueryRowContext(ctx, getNavItemByID, id)
	var i NavItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNavItemByName = `-- name: GetNavItemByName :one
SELECT id, name, url, icon, parent_id, sort_order, created_at, updated_at
FROM nav_items
WHERE name = ?
`

func (q *Queries) GetNavItemByName(ctx context.Context, name string) (NavItem, error) {
	row := q.db.QueryRowContext(ctx, getNavItemByName, name)
	var i NavItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNavItemRoles = `-- name: GetNavItemRoles :many
SELECT r.id, r.name, r.description
FROM roles r
JOIN nav_item_roles nir ON r.id = nir.role_id
WHERE nir.nav_item_id = ?
ORDER BY r.name
`

func (q *Queries) GetNavItemRoles(ctx context.Context, navItemID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getNavItemRoles, navItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNavItemsForRoles = `-- name: GetNavItemsForRoles :many
SELECT DISTINCT ni.id, ni.name, ni.url, ni.icon, ni.parent_id, ni.sort_order, ni.created_at, ni.updated_at
FROM nav_items ni
JOIN nav_item_roles nir ON ni.id = nir.nav_item_id
WHERE nir.role_id IN (/*SLICE:role_ids*/?)
ORDER BY ni.sort_order, ni.id
`

func (q *Queries) GetNavItemsForRoles(ctx context.Context, roleIds []int64) ([]NavItem, error) {
	query := getNavItemsForRoles
	var queryParams []interface{}
	if len(roleIds) > 0 {
		for _, v := range roleIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:role_ids*/?", strings.Repeat(",?", len(roleIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:role_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NavItem
	for rows.Next() {
		var i NavItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavItemChildren = `-- name: ListNavItemChildren :many
SELECT id, name, url, icon, parent_id, sort_order, created_at, updated_at
FROM nav_items
WHERE parent_id = ?
ORDER BY sort_order, id
`

func (q *Queries) ListNavItemChildren(ctx context.Context, parentID sql.NullInt64) ([]NavItem, error) {
	rows, err := q.db.QueryContext(ctx, listNavItemChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NavItem
	for rows.Next() {
		var i NavItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavItems = `-- name: ListNavItems :many
SELECT id, name, url, icon, parent_id, sort_order, created_at, updated_at
FROM nav_items
ORDER BY sort_order, id
`

func (q *Queries) ListNavItems(ctx context.Context) ([]NavItem, error) {
	rows, err := q.db.QueryContext(ctx, listNavItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NavItem
	for rows.Next() {
		var i NavItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelNavItems = `-- name: ListTopLevelNavItems :many
SELECT id, name, url, icon, parent_id, sort_order, created_at, updated_at
FROM nav_items
WHERE parent_id IS NULL
ORDER BY sort_order, id
`

func (q *Queries) ListTopLevelNavItems(ctx context.Context) ([]NavItem, error) {
	rows, err := q.db.QueryContext(ctx, listTopLevelNavItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NavItem
	for rows.Next() {
		var i NavItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromNavItem = `-- name: RemoveRoleFromNavItem :exec
DELETE FROM nav_item_roles
WHERE nav_item_id = ? AND role_id = ?
`

type RemoveRoleFromNavItemParams struct {
	NavItemID int64
	RoleID    int64
}

func (q *Queries) RemoveRoleFromNavItem(ctx context.Context, arg RemoveRoleFromNavItemParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromNavItem, arg.NavItemID, arg.RoleID)
	return err
}

const updateNavItem = `-- name: UpdateNavItem :one
UPDATE nav_items
SET name = ?, url = ?, icon = ?, parent_id = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, url, icon, parent_id, sort_order, created_at, updated_at
`

type UpdateNavItemParams struct {
	Name      string
	Url       string
	Icon      sql.NullString
	ParentID  sql.NullInt64
	SortOrder sql.NullInt64
	ID        int64
}

func (q *Queries) UpdateNavItem(ctx context.Context, arg UpdateNavItemParams) (NavItem, error) {
	row := q.db.QueryRowContext(ctx, updateNavItem,
		arg.Name,
		arg.Url,
		arg.Icon,
		arg.ParentID,
		arg.SortOrder,
		arg.ID,
	)
	var i NavItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
