// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package repository

import (
	"context"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT OR IGNORE INTO user_roles (user_id, role_id)
VALUES (?, ?)
`

type AssignRoleToUserParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const clearUserRoles = `-- name: ClearUserRoles :exec
DELETE FROM user_roles
WHERE user_id = ?
`

func (q *Queries) ClearUserRoles(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, clearUserRoles, userID)
	return err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.description
FROM roles r
JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = ?
ORDER BY r.name
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWithRole = `-- name: GetUsersWithRole :many
SELECT u.id, u.email, u.name, u.created_at, u.updated_at
FROM users u
JOIN user_roles ur ON u.id = ur.user_id
WHERE ur.role_id = ?
ORDER BY u.id
`

func (q *Queries) GetUsersWithRole(ctx context.Context, roleID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersWithRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles
WHERE user_id = ? AND role_id = ?
`

type RemoveRoleFromUserParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}
