// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, theme, created_at, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, email, name, theme, created_at, updated_at
`

type CreateUserParams struct {
	Email string
	Name  string
	Theme string
}

type CreateUserRow struct {
	ID        int64
	Email     string
	Name      string
	Theme     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.Theme)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, theme, created_at, updated_at
FROM users
WHERE email = ?
`

type GetUserByEmailRow struct {
	ID        int64
	Email     string
	Name      string
	Theme     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, theme, created_at, updated_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID        int64
	Email     string
	Name      string
	Theme     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, theme, created_at, updated_at
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID        int64
	Email     string
	Name      string
	Theme     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Theme,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = ?, name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, email, name, theme, created_at, updated_at
`

type UpdateUserParams struct {
	Email string
	Name  string
	ID    int64
}

type UpdateUserRow struct {
	ID        int64
	Email     string
	Name      string
	Theme     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Email, arg.Name, arg.ID)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTheme = `-- name: UpdateUserTheme :one
UPDATE users
SET theme = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, email, name, theme, created_at, updated_at
`

type UpdateUserThemeParams struct {
	Theme string
	ID    int64
}

type UpdateUserThemeRow struct {
	ID        int64
	Email     string
	Name      string
	Theme     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) (UpdateUserThemeRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserTheme, arg.Theme, arg.ID)
	var i UpdateUserThemeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
